/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-Cp0EpNx-WCm8VTOsBBWzSWZFwxbz4vYOdxEkKcJXmbK51wH24tSAgbjnYS7d1p6LzdfMGlz7yCzk-fVFERcRY5WOCtrWz-7odtSBKP32xs7N-NHtOvLY27SV",
  "tt": "tt-1-Zy5oHcUc2V1CSFlQpaxNU5xp7tlkwGigz2PoufKTuQQ=",
  "version": "2020-11-20"
}

export default ebconfig;